#!/bin/bash

# Created by Mostafa Hassani
# This script does most of the after install steps described in this page. https://www.tecmint.com/things-to-do-after-minimal-rhel-centos-7-installation/#C2

yum -y update && yum -y upgrade

yum install -y epel-release

yum install -y links

yum install -y gcc

yum install -y nmap

yum install -y wget

yum install -y p7zip

echo "Done."
