#!/bin/bash

# Created by Mostafa Hassani
# This script does most of the after install steps described in this page. https://www.tecmint.com/things-to-do-after-minimal-rhel-centos-7-installation/#C2


#### setting up selinux to or switching to disabled or permissive mode
sed -i s/^SELINUX=.*$/SELINUX=permissive/ /etc/selinux/config
setenforce 0

#### setting up firewall or turninn it off.
yum -y update && yum -y upgrade

yum install -y git ansible vim dstat htop iotop glances xorg-x11-xauth atop iftop wget axel nmap bind-utils net-tools conntrack yum-utils \
device-mapper-persistent-data epel-release links gcc nmap wget p7zip lvm2



echo "Done."
